import type { Location } from './types';

export const beachClubLocation: Location = {
  id: 'beach-club-1',
  name: 'Sunset Beach Club',
  floorPlanUrl: 'https://placehold.co/1200x800.png',
  objects: [
    {
      id: 'sunbed-1',
      name: 'Sunbed A1',
      type: 'sunbed',
      description: 'Prime front-row sunbed with premium towel service.',
      price: 25,
      position: { x: 15, y: 75 },
      status: 'Free',
    },
    {
      id: 'sunbed-2',
      name: 'Sunbed A2',
      type: 'sunbed',
      description: 'Prime front-row sunbed with premium towel service.',
      price: 25,
      position: { x: 20, y: 75 },
      status: 'Occupied',
    },
    {
      id: 'sunbed-3',
      name: 'Sunbed B1',
      type: 'sunbed',
      description: 'Comfortable sunbed with partial shade.',
      price: 20,
      position: { x: 17, y: 60 },
      status: 'Reserved',
    },
    {
      id: 'sunbed-4',
      name: 'Sunbed B2',
      type: 'sunbed',
      description: 'Comfortable sunbed with partial shade.',
      price: 20,
      position: { x: 22, y: 60 },
      status: 'Free',
    },
    {
      id: 'table-1',
      name: 'Cabana Table 1',
      type: 'table',
      description: 'Large table in a private cabana, perfect for groups.',
      price: 150,
      position: { x: 70, y: 25 },
      status: 'Free',
    },
    {
      id: 'table-2',
      name: 'Bistro Table 5',
      type: 'table',
      description: 'Cozy table for two near the bar.',
      price: 50,
      position: { x: 55, y: 50 },
      status: 'Occupied',
    },
    {
      id: 'boat-1',
      name: 'Jet Ski "WaveRider"',
      type: 'boat',
      description: 'High-speed jet ski for an adrenaline rush.',
      price: 90,
      position: { x: 85, y: 80 },
      status: 'Free',
    },
  ],
};
