import type { Location, Booking } from './types';

export const restaurantLocation: Location = {
  id: 'restaurant-1',
  name: 'The Gourmet Place',
  description: 'Experience the finest dining in a cozy and elegant atmosphere. Perfect for romantic dinners and special occasions.',
  floorPlanUrl: 'https://placehold.co/1200x800.png',
  objects: [
    {
      id: 'table-1',
      name: 'Table 1',
      type: 'table',
      description: 'Cozy table for two by the window.',
      price: 50,
      position: { x: 20, y: 20 },
      status: 'Free',
    },
    {
      id: 'table-2',
      name: 'Table 2',
      type: 'table',
      description: 'Cozy table for two by the window.',
      price: 50,
      position: { x: 30, y: 20 },
      status: 'Occupied',
    },
    {
      id: 'table-3',
      name: 'Table 3',
      type: 'table',
      description: 'Cozy table for two.',
      price: 45,
      position: { x: 40, y: 20 },
      status: 'Free',
    },
    {
      id: 'table-4',
      name: 'Table 4 (Large)',
      type: 'table',
      description: 'Large table for up to 8 guests.',
      price: 100,
      position: { x: 25, y: 50 },
      status: 'Reserved',
    },
    {
      id: 'table-5',
      name: 'Table 5 (Large)',
      type: 'table',
      description: 'Large table for up to 8 guests.',
      price: 100,
      position: { x: 45, y: 50 },
      status: 'Free',
    },
    {
      id: 'table-6',
      name: 'Table 6',
      type: 'table',
      description: 'Standard table for four.',
      price: 70,
      position: { x: 70, y: 20 },
      status: 'Free',
    },
    {
      id: 'table-7',
      name: 'Table 7',
      type: 'table',
      description: 'Standard table for four.',
      price: 70,
      position: { x: 80, y: 20 },
      status: 'Occupied',
    },
    {
        id: 'table-8',
        name: 'Table 8 (Booth)',
        type: 'table',
        description: 'Comfortable booth for up to 6 people.',
        price: 90,
        position: { x: 75, y: 70 },
        status: 'Free',
    },
    {
        id: 'table-9',
        name: 'Table 9 (Booth)',
        type: 'table',
        description: 'Comfortable booth for up to 6 people.',
        price: 90,
        position: { x: 75, y: 85 },
        status: 'Free',
    },
  ],
};

export const beachClubLocation: Location = {
  id: 'beach-club-1',
  name: 'Sunset Beach Club',
  description: 'Relax by the sea with our premium sunbeds, refreshing cocktails, and live DJ sets.',
  floorPlanUrl: 'https://placehold.co/1200x800.png',
  objects: [
    {
      id: 'sunbed-1',
      name: 'Sunbed A1',
      type: 'sunbed',
      description: 'Prime front-row sunbed with premium towel service.',
      price: 25,
      position: { x: 15, y: 75 },
      status: 'Free',
    },
    {
      id: 'sunbed-2',
      name: 'Sunbed A2',
      type: 'sunbed',
      description: 'Prime front-row sunbed with premium towel service.',
      price: 25,
      position: { x: 20, y: 75 },
      status: 'Occupied',
    },
    {
      id: 'table-1',
      name: 'Cabana Table 1',
      type: 'table',
      description: 'Large table in a private cabana, perfect for groups.',
      price: 150,
      position: { x: 70, y: 25 },
      status: 'Free',
    },
     {
      id: 'boat-1',
      name: 'Jet Ski "WaveRider"',
      type: 'boat',
      description: 'High-speed jet ski for an adrenaline rush.',
      price: 90,
      position: { x: 85, y: 80 },
      status: 'Free',
    },
  ],
};

export const coworkingLocation: Location = {
  id: 'coworking-1',
  name: 'Productivity Hub',
  description: 'A modern co-working space with high-speed internet, meeting rooms, and unlimited coffee.',
  floorPlanUrl: 'https://placehold.co/1200x800.png',
  objects: [
    {
      id: 'workspace-1',
      name: 'Hot Desk 1',
      type: 'workspace',
      description: 'Shared desk with access to all amenities.',
      price: 15,
      position: { x: 10, y: 20 },
      status: 'Free',
    },
    {
      id: 'workspace-2',
      name: 'Dedicated Desk D5',
      type: 'workspace',
      description: 'Your own personal desk with lockable storage.',
      price: 150,
      position: { x: 40, y: 40 },
      status: 'Occupied',
    },
    {
      id: 'room-1',
      name: 'Meeting Room "Apollo"',
      type: 'room',
      description: 'Large meeting room for up to 12 people with video conferencing.',
      price: 75,
      position: { x: 80, y: 50 },
      status: 'Reserved',
    },
  ],
};

export const mockBookings: Booking[] = [
    {
        id: 'booking-1',
        objectName: 'Table 5 (Large)',
        locationName: 'The Gourmet Place',
        customerName: 'John Doe',
        bookingDate: new Date().toLocaleDateString(),
        status: 'Confirmed'
    },
    {
        id: 'booking-2',
        objectName: 'Sunbed A1',
        locationName: 'Sunset Beach Club',
        customerName: 'Jane Smith',
        bookingDate: new Date(new Date().setDate(new Date().getDate() + 2)).toLocaleDateString(),
        status: 'Confirmed'
    },
    {
        id: 'booking-3',
        objectName: 'Meeting Room "Apollo"',
        locationName: 'Productivity Hub',
        customerName: 'Acme Inc.',
        bookingDate: new Date().toLocaleDateString(),
        status: 'Confirmed'
    },
    {
        id: 'booking-4',
        objectName: 'Table 1',
        locationName: 'The Gourmet Place',
        customerName: 'Peter Jones',
        bookingDate: new Date(new Date().setDate(new Date().getDate() - 5)).toLocaleDateString(),
        status: 'Cancelled'
    },
];
