import type { Location } from './types';

export const restaurantLocation: Location = {
  id: 'restaurant-1',
  name: 'The Gourmet Place',
  floorPlanUrl: 'https://placehold.co/1200x800.png',
  objects: [
    {
      id: 'table-1',
      name: 'Table 1',
      type: 'table',
      description: 'Cozy table for two by the window.',
      price: 50,
      position: { x: 20, y: 20 },
      status: 'Free',
    },
    {
      id: 'table-2',
      name: 'Table 2',
      type: 'table',
      description: 'Cozy table for two by the window.',
      price: 50,
      position: { x: 30, y: 20 },
      status: 'Occupied',
    },
    {
      id: 'table-3',
      name: 'Table 3',
      type: 'table',
      description: 'Cozy table for two.',
      price: 45,
      position: { x: 40, y: 20 },
      status: 'Free',
    },
    {
      id: 'table-4',
      name: 'Table 4 (Large)',
      type: 'table',
      description: 'Large table for up to 8 guests.',
      price: 100,
      position: { x: 25, y: 50 },
      status: 'Reserved',
    },
    {
      id: 'table-5',
      name: 'Table 5 (Large)',
      type: 'table',
      description: 'Large table for up to 8 guests.',
      price: 100,
      position: { x: 45, y: 50 },
      status: 'Free',
    },
    {
      id: 'table-6',
      name: 'Table 6',
      type: 'table',
      description: 'Standard table for four.',
      price: 70,
      position: { x: 70, y: 20 },
      status: 'Free',
    },
    {
      id: 'table-7',
      name: 'Table 7',
      type: 'table',
      description: 'Standard table for four.',
      price: 70,
      position: { x: 80, y: 20 },
      status: 'Occupied',
    },
    {
        id: 'table-8',
        name: 'Table 8 (Booth)',
        type: 'table',
        description: 'Comfortable booth for up to 6 people.',
        price: 90,
        position: { x: 75, y: 70 },
        status: 'Free',
    },
    {
        id: 'table-9',
        name: 'Table 9 (Booth)',
        type: 'table',
        description: 'Comfortable booth for up to 6 people.',
        price: 90,
        position: { x: 75, y: 85 },
        status: 'Free',
    },
  ],
};

export const beachClubLocation: Location = {
  id: 'beach-club-1',
  name: 'Sunset Beach Club',
  floorPlanUrl: 'https://placehold.co/1200x800.png',
  objects: [
    {
      id: 'sunbed-1',
      name: 'Sunbed A1',
      type: 'sunbed',
      description: 'Prime front-row sunbed with premium towel service.',
      price: 25,
      position: { x: 15, y: 75 },
      status: 'Free',
    },
    {
      id: 'sunbed-2',
      name: 'Sunbed A2',
      type: 'sunbed',
      description: 'Prime front-row sunbed with premium towel service.',
      price: 25,
      position: { x: 20, y: 75 },
      status: 'Occupied',
    },
    {
      id: 'table-1',
      name: 'Cabana Table 1',
      type: 'table',
      description: 'Large table in a private cabana, perfect for groups.',
      price: 150,
      position: { x: 70, y: 25 },
      status: 'Free',
    },
     {
      id: 'boat-1',
      name: 'Jet Ski "WaveRider"',
      type: 'boat',
      description: 'High-speed jet ski for an adrenaline rush.',
      price: 90,
      position: { x: 85, y: 80 },
      status: 'Free',
    },
  ],
};

export const coworkingLocation: Location = {
  id: 'coworking-1',
  name: 'Productivity Hub',
  floorPlanUrl: 'https://placehold.co/1200x800.png',
  objects: [
    {
      id: 'workspace-1',
      name: 'Hot Desk 1',
      type: 'workspace',
      description: 'Shared desk with access to all amenities.',
      price: 15,
      position: { x: 10, y: 20 },
      status: 'Free',
    },
    {
      id: 'workspace-2',
      name: 'Dedicated Desk D5',
      type: 'workspace',
      description: 'Your own personal desk with lockable storage.',
      price: 150,
      position: { x: 40, y: 40 },
      status: 'Occupied',
    },
    {
      id: 'room-1',
      name: 'Meeting Room "Apollo"',
      type: 'room',
      description: 'Large meeting room for up to 12 people with video conferencing.',
      price: 75,
      position: { x: 80, y: 50 },
      status: 'Reserved',
    },
  ],
};
